site_name: Querpyable
site_description: "A Python implementation of LINQ"
site_url: "https://billsioros.github.io/querpyable/"
repo_url: "https://github.com/billsioros/querpyable"
edit_uri: "edit/master/docs/"
repo_name: "billsioros/querpyable"
copyright: |
  Copyright &copy; 2024-2024 <a href="https://github.com/billsioros" target="_blank" rel="noopener">Vasilis Sioros</a>
nav:
  - Overview: index.md
  - Code Reference: src/querpyable.md
  - Contributing:
      - Contributing Guidelines: CONTRIBUTING.md
      - Code Of Conduct: CODE_OF_CONDUCT.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md
theme:
  name: material
  features:
    - search.suggest
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
          options:
            show_source: false
            docstring_style: google
            merge_init_into_class: yes
            docstring_options:
              ignore_init_summary: yes
              show_submodules: no
  - minify:
      minify_html: true
markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: ¤
  - mdx_truly_sane_lists
watch:
  - src/querpyable
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/billsioros
  version:
    provider: mike
